site_name: Blog Informático de Juandi
nav:
- Home: index.html
- Sobre mi: sobremi.md

theme: material
  palette:
    primary: 'red'
    accent: 'red'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  logo: 'img/favicon.ico'
  favicon: 'img/favicon.ico'
  language: 'es'
  feature:
    tabs: true 
